name: Update website data

on: workflow_dispatch
#  schedule:
#    - cron: '0 0 1 * *'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyyaml requests

    - name: Call Airtable API and convert to YAML
      run: |
        python scripts/update_data.py
      env:
        EAISEL_AIRTABLE_API_KEY: ${{ secrets.EAISEL_AIRTABLE_API_KEY }}
        EAISEL_AIRTABLE_BASE_ID: ${{ secrets.EAISEL_AIRTABLE_BASE_ID }}
        EAISEL_AIRTABLE_TABLE_ID: ${{ secrets.EAISEL_AIRTABLE_TABLE_ID }}
        EAISEL_AIRTABLE_VIEW_ID: ${{ secrets.EAISEL_AIRTABLE_VIEW_ID }}
        EAISEL_AIRTABLE_EVENTS_TABLE_ID: ${{ secrets.EAISEL_AIRTABLE_EVENTS_TABLE_ID }}
        EAISEL_AIRTABLE_EVENTS_VIEW_ID: ${{ secrets.EAISEL_AIRTABLE_EVENTS_VIEW_ID }}
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update site data'
        file_pattern: _data/*.yml